remote_theme: pages-themes/dinky@v0.2.0
title: Vtunes Charts
description: All data hand-picked from the RC discord server.
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true